# Generated by Django 2.1.5 on 2020-04-24 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oficina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=30)),
                ('precio', models.FloatField(blank=True, default=None, null=True)),
                ('tipo_contrato', models.CharField(max_length=20)),
                ('ubicacion', models.CharField(max_length=40)),
                ('localidad', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=500)),
                ('duenio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.Usuario')),
            ],
        ),
    ]
