# Generated by Django 2.1.5 on 2020-04-24 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficina', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oficina',
            name='foto',
            field=models.CharField(max_length=300),
        ),
    ]
