# Generated by Django 3.0.5 on 2020-04-28 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficina', '0002_auto_20200424_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='oficina',
            name='foto360',
            field=models.CharField(default='https://panoraven.com/es/embed/NcHvNymjMI', max_length=1000),
            preserve_default=False,
        ),
    ]
