# Generated by Django 2.1.5 on 2020-05-02 00:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficina', '0003_oficina_foto360'),
    ]

    operations = [
        migrations.AddField(
            model_name='oficina',
            name='parqueadero',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
    ]
