# Generated by Django 2.1.5 on 2020-05-02 00:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficina', '0005_auto_20200501_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='oficina',
            name='calificacion',
            field=models.FloatField(default=3.5, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
    ]
