# Generated by Django 2.1.5 on 2020-05-02 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oficina', '0006_oficina_calificacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oficina',
            old_name='moditorunico',
            new_name='monitorunico',
        ),
    ]
