# Generated by Django 2.2 on 2020-05-06 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficina', '0007_auto_20200501_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oficina',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
