# Generated by Django 2.1.5 on 2020-05-10 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oficina', '0008_auto_20200505_1918'),
        ('oficina', '0008_auto_20200506_1900'),
    ]

    operations = [
    ]
