# Generated by Django 2.1.5 on 2020-05-10 23:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficina', '0011_historial_tipo_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='historial',
            name='calificacion',
            field=models.FloatField(default=4.5, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
    ]
