# Generated by Django 2.1.5 on 2020-05-11 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficina', '0013_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='oficina',
            name='interesados',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='oficina',
            name='porcentaje',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='oficina',
            name='visitantes',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
